### ISSUE TITLE
Plus de tracker via api bbox

### ISSUE THREAD

**Issue by Percherie** [earion68/hass_custom_bbox#5]
Bonjour, 

Hier j'ai redémarrer ma bbox et depuis les tracker ne remontent plus.

J'ai des retours de log dans HA, il semble avoir des problèmes sur l'api
Ma version de bbox est la 23.7.8

Log après redémarrage de HA ce matin
```
Logger: homeassistant.components.device_tracker
Source: components/device_tracker/legacy.py:301
Integration: Dispositif de suivi (documentation, issues)
First occurred: 08:27:06 (1 occurrences)
Last logged: 08:27:06

Error setting up platform legacy custom_bbox
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 301, in async_setup_legacy
    scanner = await hass.async_add_executor_job(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/device_tracker.py", line 35, in get_scanner
    scanner = BboxDeviceScanner(config[DOMAIN])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/device_tracker.py", line 54, in __init__
    self.success_init = self._update_info()
                        ^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/device_tracker.py", line 82, in _update_info
    result = box.get_all_connected_devices()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/pybbox.py", line 116, in get_all_connected_devices
    resp = api.execute_api_request()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/bboxApiCall.py", line 62, in execute_api_request
    raise Exception('Error {} with request {}'.format(
Exception: Error 401 with request http://192.168.1.254/api/v1/hosts
```

**Comment by earion68** [comment]
il semble y avoir un souci avec le nouveau firmware (voir #4)
j'attends la mise à jour sur ma Bbox pour pouvoir tester et tenter de réparer.

**Comment by Percherie** [comment]
Si il y a des éléments que je puisse tester pour remonter les infos de la nouvelle api pense à me l'indiquer. Je pourrais regarder dimanche soir ce qui remonte

**Comment by Percherie** [comment]
Si il y a des éléments que je puisse tester pour remonter les infos de la nouvelle api pense à me l'indiquer. Je pourrais regarder dimanche soir ce qui remonte

**Comment by earion68** [comment]
J'ai enfin reçu la mise à jour.

J'ai commit un quick fix dans la branche **quickfix_login** et le commit https://github.com/earion68/hass_custom_bbox/commit/c6a150e5959b0ef5f855ac43f5e09b131feee455 en particulier 
mot de passe de ta Bbox à mettre en dur pour le moment.
Aussi, la Bbox doit répondre à son addresse mabbox.bytel.fr.

Chez moi ça fonctionne à nouveau. Tu peux me dire si ça fait le job chez toi ? Si oui je regarderai pour instrumentaliser un peu via la config du composant.

![image](https://github.com/earion68/hass_custom_bbox/assets/54678154/0479eca8-b1fc-4f24-9c52-dbb263fa9241)

**Comment by Percherie** [comment]
Est-ce que le mot de passe doit être entre les crochets ?

**Comment by earion68** [comment]
Non


________________________________

**Comment by Percherie** [comment]
Me changement concernant l'adresse IP ne semble pas correctement fonctionner.
Voici le retour de log

```
Logger: homeassistant.components.device_tracker
Source: components/device_tracker/legacy.py:301
Integration: Dispositif de suivi (documentation, issues)
First occurred: 16:33:38 (1 occurrences)
Last logged: 16:33:38

Error setting up platform legacy custom_bbox
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 301, in async_setup_legacy
    scanner = await hass.async_add_executor_job(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/device_tracker.py", line 35, in get_scanner
    scanner = BboxDeviceScanner(config[DOMAIN])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/device_tracker.py", line 54, in __init__
    self.success_init = self._update_info()
                        ^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/device_tracker.py", line 82, in _update_info
    box = Bbox(ip='mabbox.bytel.fr')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/pybbox.py", line 25, in __init__
    self.bbox_url = BboxAPIUrl(None, None, ip)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/bboxApiURL.py", line 25, in __init__
    self.build_url_request()
  File "/config/custom_components/custom_bbox/bboxApiURL.py", line 53, in build_url_request
    if net.IPAddress(self.ip).is_private():
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/netaddr/ip/__init__.py", line 341, in __init__
    raise AddrFormatError('failed to detect a valid IP ' 'address from %r' % addr)
netaddr.core.AddrFormatError: failed to detect a valid IP address from 'mabbox.bytel.fr'

```

**Comment by earion68** [comment]
Oui ça devrait


________________________________

**Comment by Percherie** [comment]
Y a de l'amélioration, c'est maintenant l'étape login qui couine

```
Logger: homeassistant.components.device_tracker
Source: components/device_tracker/legacy.py:301
Integration: Dispositif de suivi (documentation, issues)
First occurred: 18:46:05 (1 occurrences)
Last logged: 18:46:05

Error setting up platform legacy custom_bbox
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 301, in async_setup_legacy
    scanner = await hass.async_add_executor_job(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/device_tracker.py", line 35, in get_scanner
    scanner = BboxDeviceScanner(config[DOMAIN])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/device_tracker.py", line 54, in __init__
    self.success_init = self._update_info()
                        ^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/device_tracker.py", line 83, in _update_info
    box.login("Ubumob.BBX65")
  File "/config/custom_components/custom_bbox/pybbox.py", line 150, in login
    response = api.execute_api_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/bboxApiCall.py", line 62, in execute_api_request
    raise Exception('Error {} with request {}'.format(
Exception: Error 404 with request http://mabbox.bytel.fr/api/v1/login
```

**Comment by earion68** [comment]
Même problème ici. J'ai dû redescendre une image de Home Assistant pour que ça fonctionne, je comprenais pas...

Si tu es sur Docker ce sera facile à faire.


________________________________

**Comment by Percherie** [comment]
C'est sur une VM, je verrais en rentrant pour reconstruire ça manuellement 

Ça fonctionne chez toi avec les modifications ?

**Comment by earion68** [comment]
Oui. J'ai galéré à comprendre mais ça devait être un souci de cache Python, si ça fait le moindre sens...

Je devrais pouvoir finaliser le correctif rapidement pour éviter d'avoir tout en dur


________________________________

**Comment by earion68** [comment]
J'ai finalisé le correctif et mergé dans la branche **main**, tu peux récupérer l'ensemble des fichiers.

Attention il y a un breaking change: il faut ajouter le mot de passe de la bbox dans la clé "password" du configuration.yaml, c.f. https://github.com/earion68/hass_custom_bbox/blob/main/README.md

Merci de me confirmer quand le problème est corrigé de ton côté pour que je puisse fermer le ticket.

**Comment by Percherie** [comment]
Merci je vais tester ça 

Pour le stockage du mot de passe, est-ce que l'usage de !secret est compatible ? Pour ne pas à faire fuiter les mdp en cas de partage du fichier de configuration

**Comment by Percherie** [comment]
Je valide les modifications

Les erreurs venait de la ligne dans le fichier de configuration host: mabbox.bytel.fr # optional

Si je supprime cette ligne, le tracker fonctionne correctement. Je n'ai pas modifié la configuration réseau de la Bbox, elle est joignable uniquement depuis le réseau local (pas d'accès depuis le web)

Ps : pense à mettre à jour le fichier readme ;-p

**Comment by supiotjc** [comment]
Bonjour. Impossible chez moi de faire fonctionner l'intégration.
En changeant la ligne host, en l'enlevant, rien n'y fait.
J'ai désinstallé et réinstallé l'intégration. Nada.

`Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:344
Integration: Capteur (documentation, issues)
First occurred: 18:52:56 (1 occurrences)
Last logged: 18:52:56

Error while setting up custom_bbox platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/sensor.py", line 105, in setup_platform
    bbox_data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/sensor.py", line 207, in update
    box.login(self.password)
  File "/config/custom_components/custom_bbox/pybbox.py", line 150, in login
    response = api.execute_api_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/bboxApiCall.py", line 62, in execute_api_request
    raise Exception('Error {} with request {}'.format(
Exception: Error 201 with request https://mabbox.bytel.fr/api/v1/login
`

`Logger: homeassistant.components.device_tracker
Source: components/device_tracker/legacy.py:301
Integration: Dispositif de suivi (documentation, issues)
First occurred: 18:53:06 (1 occurrences)
Last logged: 18:53:06

Error setting up platform legacy custom_bbox
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 301, in async_setup_legacy
    scanner = await hass.async_add_executor_job(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/device_tracker.py", line 39, in get_scanner
    scanner = BboxDeviceScanner(config[DOMAIN])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/device_tracker.py", line 59, in __init__
    self.success_init = self._update_info()
                        ^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/device_tracker.py", line 87, in _update_info
    box.login(self.password)
  File "/config/custom_components/custom_bbox/pybbox.py", line 150, in login
    response = api.execute_api_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/bboxApiCall.py", line 62, in execute_api_request
    raise Exception('Error {} with request {}'.format(
Exception: Error 201 with request https://mabbox.bytel.fr/api/v1/login
`

`BOX
ModèleF@st 5688b Numéro de série127690211502162 
LOGICIEL
Version du firmware opérationnelSG_MAIN_15.014 Date du firmware opérationnel20.11.2023 Version du firmware de secoursSG_MAIN_10.022 Date du firmware de secours18.10.2022 Version du loader 12019.07@sc-3.80.0-sec Version du loader 22017.09@sc-0.52.6-sec Version du SPL1.10.4 Version du TPL1.10.4
`
