### ISSUE TITLE
Nouvelle BBOX Wifi 6E

### ISSUE THREAD

**Issue by soundboy974** [earion68/hass_custom_bbox#8]
Bonjour,

J'ai à la maison la nouvelle BBOX F@st 5688b (Wifi 6E).
Savez vous si le l'intégration sera un jour compatible avec ce modèle.
Pour le moment, j'obtiens le message d'erreur "Connection timed out" avec mon Dyndns.

Merci d'avance

**Comment by Mr3k** [comment]
Bonjour je suis également intéressée par cette intégration. 
Pour le moment j'obtiens l'erreur suivante :

 File "/config/custom_components/custom_bbox/bboxApiCall.py", line 62, in execute_api_request
    raise Exception('Error {} with request {}'.format(
Exception: Error 400 with request https://mabbox.bytel.fr/api/v1/login
2024-04-19 14:55:40.334 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 468, in async_device_tracker_scan
    found_devices = await scanner.async_scan_devices()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 984, in async_scan_devices
    return await self.hass.async_add_executor_job(self.scan_devices)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/device_tracker.py", line 64, in scan_devices
    self._update_info()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 191, in wrapper
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/device_tracker.py", line 87, in _update_info
    box.login(self.password)
  File "/config/custom_components/custom_bbox/pybbox.py", line 150, in login
    response = api.execute_api_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
Cordialement
